#!/usr/bin/env python
# -*- coding:utf-8 -*- 
def get_local_ip(ifname):
    import socket, fcntl, struct
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    inet = fcntl.ioctl(s.fileno(), 0x8915, struct.pack('256s', ifname[:15]))
    ret = socket.inet_ntoa(inet[20:24])
    return ret

def config_file():
    ip = get_local_ip('enp0s25')
    fd = open('/tmp/myscp_config', 'wb+')
    fd.writelines('IP=%s' % (str(ip)+'\n'))
    fd.writelines('NAME=liubo'+'\n')

import os
import subprocess
def scp():
    p = subprocess.Popen("/usr/bin/scp %s %s@%s:%s" % ('/tmp/myscp_config','liubo0922', '192.168.9.115', '~/.myscp_config'), shell = True)
    p.communicate()


import time
if __name__ == '__main__':
    time.sleep(2)
    config_file()
    scp()




