#!/bin/bash

index_dir="\
        ./abi/  \
        ./bionic/ \
        ./bootable/ \
        ./hardware/ \
        ./frameworks/ \
        ./cts/ \
        ./system/ \
        ./abi/ \
        ./bionic/ \
        ./external/tiny* \
        ./external/bluetooth/ \
        ./external/libselinux/ \
        ./kernel \
        ./vendor \
        ./libnativehelper \
        ./libcore    \
        ./dalvik     \
        ./device     \
        ./packages   \
       ./App\
    ./Bsp \
    ./CMSIS \
    ./Drivers \
    ./Emlib \
    ./UC_CPU \
    ./UC_LIB \
    ./UC_OS \
    ./adsp_proc \
    ./common\
    ./lpass_proc \
    ./modem_proc\
    ./rpm_proc \
    ./wcnss_proc

        "

filter_dir="\
        ./out \
        ./git \
        ./hardware/ti \
        "

ftype="*.c *.java *.h *.cpp"

###########################################################

fil_dir="-wholename xx -prune"
for i in $filter_dir
do
        fil_dir="$fil_dir -o -wholename $i -prune"
done

file_type=""

for i in $ftype
do 
        file_type="$file_type -o -name $i "
done

filelist="/tmp/filelist.$RANDOM"

#-exec readlink -f {} \; \
#echo "$index_dir"
#echo "$fil_dir"
#echo "$file_type"
#echo "$filelist"

find    $index_dir     \
        $fil_dir    \
        $file_type  \
        1>$filelist \
        2>/dev/null

CUR_PATH=`pwd`

if [ $# == 0 ]; then
    echo "No input arg, use default"
    rm -f tags
    ctags  --c-kinds=+cdefgmnpstuv --c++-kinds=+cdefgmnpstuv --fields=+iaS --extra=+q -L $filelist 2>/dev/null
    exit 0;
fi

while getopts "f:" arg
do
    case $arg in
        f )
            ctags -f $CUR_PATH/$OPTARG --c-kinds=+cdefgmnpstuv --c++-kinds=+cdefgmnpstuv --fields=+iaS --extra=+q -L $filelist 2>/dev/null
            ;;
        * )
            echo "unkonw argument use default"
            rm -f tags
            ctags  --c-kinds=+cdefgmnpstuv --c++-kinds=+cdefgmnpstuv --fields=+iaS --extra=+q -L $filelist 2>/dev/null
            ;;
    esac
done

